pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'php:7-cli'

name: My Cool Build
trigger:
- azure-pipelines
- releases/*

steps:
  script: docker build -t $(dockerId)/$(dockerImage) .
  displayName: 'docker build'
