pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'phpluralize:$(build.buildId)'

name: My Cool Build
trigger:
- azure-pipelines
- releases/*

steps:
- script: docker build -f dockerfile -t $(phpluralize) .
  displayName: 'docker build'
